 <div class="line_center_container"></div>
	<div id="head_center_container">
		<div id="contain_head_center_container">
				<div id="left_contain_head_center_container">
					<a href="#">Home</a> > <a href="#">Online Store</a> > Edit Shipping Method 
				</div>
		</div>
	</div>
<div class="line_center_container"></div>
<div class="allowed_country">  
   <h3>Complete</h3>
	<div class="delimiter"></div>
<p>You order susseful completed.</p>
<p>You order number is <span class="red_big_bold"> <?=$_SESSION['num']?> </span> <span class="bold">please, remember it</span></p>
</div>