
<div class="line_center_container"></div>
<div id="head_center_container">
<div id="contain_head_center_container">
<div id="right_contain_head_center_container"></div>
<div id="left_contain_head_center_container"><a href="#">Home</a> >
Online Store</div>
</div>
</div>
<div class="line_center_container"></div>
<div class="cart_big_title">Checkout</div>
<div class="step_for_ships">
<div class="step_for_ships_container_4">
<p>Shipping address</p>
<p>Ship Methods</p>
<p>Payment Method</p>
<a href="#">Complete Order</a></div>
</div>
<div class="cart_title_bar">
<div class="cart_product_name_title">Name</div>
<div class="cart_product_SKU_title">SKU</div>
<div class="cart_product_price_title">Price</div>
<div class="cart_product_quantity_title">Quantity / Update</div>
<div class="cart_product_subtotal_title">Subtotal</div>
</div>
<!--Содержимое корзины -->
<!--Содержимое корзины -->
<?php $total = 0; foreach($this->products as $product):?>
<div class="cart_product_container">
<div class="cart_product_name"><a
	href="/product/index/id/<?=$product['product']['id']?>"><?=$product['product']['title']?></a></div>
<div class="cart_product_SKU">NBK-AS-T91-BK</div>
<div class="cart_product_price"><?=$this->valute($product['product']['price'])?></div>
<div class="cart_product_quantity"><input type="text"
	value="<?=$product['count']?>"> <a href="#" class="plus"><img
	src="/application/public/img/qty-more.png"></a> <a href="#"
	class="minus"><img src="/application/public/img/remove_f.png"></a> <span
	class="price_" style="display: none"><?=$product['product']['price']?></span>
<span class="product_id" style="display: none;"><?=$product['product']['id']?></span>
</div>
<div class="cart_product_subtotal"><?=$this->valute($product['product']['price'] * $product['count'], 'subprice')?></span></div>
</div>
<?php $total+=$product['product']['price'] * $product['count']?>
<?php endforeach;?>
<!--Конец блока содержимого корзины -->

<!-- <div class="sum_cart_block">
			<div class="sum_cart_block_price">AU $2,572.00</div>
			Subtotal:
		</div> -->

<div class="sum_cart_block">
<div class="sum_cart_block_price">
<p><?=$this->valute($total,'total')?></span></p>
</div>
<p>Total:</p>
</div>
<!--<div class="sum_cart_block">
			<div class="sum_cart_block_price">AU $2,572.00</div>
			GST Included in Total: 
		</div> -->
<div class="line_center_container"></div>
<div class="shipto-addresses-block-inner">
<div class="please_select"><span>Please review the provided data and
confirm the order!</span></div>

<table>
	<tr>
		<td><span>Shipping Address:</span></td>
		<?php if(!$this->adress):
		$adress = Zend_Auth::getInstance()->getIdentity();
		else:
		$adress = $this->adress;
		endif;
		?>
		<td><?=$adress->firstname . ' ' . $adress->middlename . ' ' . $adress->lastname?></td>
	</tr>

	<tr>
		<td></td>
		<?php $country = new Country();
		$country = $country->getCountry($adress->country);
		?>
		<td><?=$country->name?></td>
	</tr>

	<tr>
		<td></td>
		<td><?=$adress->state?></td>
	</tr>
	<tr>
		<td></td>
		<td><?=$adress->city?></td>
	</tr>
	<tr>
		<td></td>
		<td><?=$adress->zip?></td>
	</tr>
	<tr>
		<td></td>
		<td><?=$adress->adress?></td>
	</tr>
	<tr>
		<td></td>
		<td><?=$adress->adress2?></td>
	</tr>
	<tr>
		<td></td>
		<td><?=$adress->phone?></td>
	</tr>
	<tr>
		<td></td>
		<td><?=$adress->mobilephone?></td>
	</tr>
	<tr>
		<td><span>Shipping Rate:</span></td>
		<td><?=$this->shipping->text?></td>
	</tr>
	<tr>
		<td><span>Payment Method:</span></td>
		<td><?php switch($this->payment){
			case 'bank': echo "Bank Transfer"; break;
			case 'paypal': echo "PayPal (+ AU $17.48)"; break;
			case 'credit': echo "<p>Credit Card : </p>";
			if($_SESSION['cardName'] == 'visa'){echo "<p>Visa</p>";} else {echo "<p>Master Card</p>";}
			echo"<p>{$_SESSION['cardNumber']}</p>";
			echo "<p>{$_SESSION['cardCode']}</p>";
			echo "<p>{$_SESSION['mounth']} / {$_SESSION['year']}</p>";
			break;
		}?></td>
	</tr>
</table>

<div id="special_notes">
<p>Please leave a note to us with your order if you want to:</p>
<form action="/order/create/" method="post" id="commentform"><textarea
	name="comment"></textarea> <input type="submit" id="confirm"
	value="Confirm Order"></form>
</div>
</div>
<div class="line_center_container"></div>
<script type="text/javascript">
					function getTotalPrice(){
						total = 0;
						$('.subprice').each(function(){
							val = parseInt($(this).text());
							total += val
						})
						return total;
					}
					
					$('.plus').click(function(){
						input = $(this).parent().children('input');
						val  = parseInt($(input).val());
						$(input).val(val+1);
						
						price = parseInt($(input).parent().children('.price_').text());
						$(input).parent().parent().children('.cart_product_subtotal').children('.subprice').text(price  * (val+1));
						$('.total').text(getTotalPrice());
						product_id = parseInt($(input).parent().children('.product_id').text());
						val  = parseInt($(input).val());
						 $.ajax({
							   type: "POST",
							   url: "/cart/updatecount/count/"+val,
							   data: "product_id=" + product_id,
							   success: function(msg){
							   }
							 });
						return false;
					})
					$('.minus').click(function(){
						input = $(this).parent().children('input');
						val = parseInt($(input).val());
						val--;
						$(input).val(val);
						if(val>0){
							price = parseInt($(input).parent().children('.price_').text());
							$(input).parent().parent().children('.cart_product_subtotal').children('.subprice').text(price  * (val-1));
							$('.total').text(getTotalPrice());
						}
						product_id = parseInt($(input).parent().children('.product_id').text());
						val = parseInt($(input).val());
						 $.ajax({
							   type: "POST",
							   url: "/cart/updatecount/count/"+val,
							   data: "product_id=" + product_id,
							   success: function(msg){}
						 });
							if(val<1){
								$(input).parent().parent().remove();
								$('.total').text(getTotalPrice());
							}
						return false;
					})
					$('.shipping').click(function(){
						val = $(this).val();
						$.ajax({
							   url: "/shipping/set/val/"+val,
							   success: function(msg){}
						});
					})
					$('#confirm').click(function(){
						data = $('#commentform').serialize();
					    $.ajax({
					    	   type: "POST",
					    	   data: data,
							   url: "/order/create/",
							   success: function(msg){
					    			window.location.href="/order/complete/"
							   }
						 });
						 return false;
					})
				</script>
