
<div class="line_center_container"></div>
				<div id="head_center_container">
					<div id="contain_head_center_container">
						<div id="right_contain_head_center_container"></div>
						<div id="left_contain_head_center_container">
							<a href="#">Home</a> > Online Store
						</div>
					</div>
				</div>
<div class="line_center_container"></div>
<div class="cart_big_title">Checkout</div>
<div class="checkout_information">
	<p>Please log in if you have an account, or enter your contact details below, to allow us to
	 calculate your exact order total based on your delivery address and payment options.</p>
	 <p>Our entire Checkout process is protected by 128-bit or higher Encryption to keep your 
	 personal details totally secure, and will never share your contact details with anyone.</p>
</div>
<div class="checkout_line">
	<div class="checkout_line_up"></div>
	<div class="checkout_line_down"></div>
</div>

<div class="checkout_radio_zone">
	<input type="radio">
	Returning Customers: Please Log In
</div>
<form action="/user/login/checkout/1/" method="POST">
	<div class="checkout_login_zone">
		<div class="checkout_login_string">Username:<input type="text" name="login"> </div>
		<div class="checkout_login_string">Password :<input type="password" name="pass"> ( <a href="#">Lost Password?</a>)</div>
	</div>
	<?php // @todo если доебутся сделать нормальную кнопку ?>
     	<input class="checkout_zone_login_button" type="submit" value="Login">
		<div class="remember_me">Remember me: <input type="checkbox" name="remember"> </div>
</form>
<div class="checkout_line">
	<div class="checkout_line_up"></div>
	<div class="checkout_line_down"></div>
</div>
<div class="checkout_radio_zone">
	<input type="radio">
	New Customers: Please Start Here
</div>
<p class="required">(* = Required)</p>
	<div class="registration_title">Customer Information</div>
<form action="/user/register/checkout/1/" method="post">
    <p class="register_text">Mail* : </p>
	<p class="register_input"><input type="text" name="mail"></p>
	<div class="clear"></div>
    <p class="register_text">login* :</p>
   	<p class="register_input"><input type="text" name="login"></p>
	<div class="clear"></div>
    <p class="register_text">password* :</p>
    <p class="register_input"><input type="password" name="pass"></p>
	<div class="clear"></div>
    <p class="register_text">Confirm Password*" :</p>
    <p class="register_input"><input type="password" name="repass"></p>
	<div class="delimiter"></div>
    <div class="clear"></div>
	<div class="line_center_container"></div>
	<div class="delimiter"></div>
	<div class="registration_title">Bill To Information</div>
    <p class="register_text">Company Name :</p>
	<p class="register_input"><input type="text" name="company"></p>
	<div class="clear"></div>
    <p class="register_text">Title: </p>
	<p class="register_input">
    <select name="title" id="title_field">
        <option value="">none</option>
        <option value="Mr.">Mr.</option>
        <option value="Mrs.">Mrs.</option>
        <option value="Dr.">Dr.</option>
        <option value="Prof.">Prof.</option>
    </select>
    </p>
	<div class="clear"></div>
    <p class="register_text">First Name* :</p>
    <p class="register_input"><input type="text" name="firstname"></p>
	<div class="clear"></div>
    <p class="register_text">Last Name* :</p>
    <p class="register_input"><input type="text" name="lastname"></p>
	<div class="clear"></div>
    <p class="register_text">Middle Name :</p>
    <p class="register_input"><input type="text" name="middlename"></p>
	<div class="clear"></div>
    <p class="register_text">Address 1* :</p>
    <p class="register_input"><input type="text" name="adress"></p>
	<div class="clear"></div>
    <p class="register_text">Address 2 :</p>
    <p class="register_input"><input type="text" name="adress2"></p>
	<div class="clear"></div>
    <p class="register_text">City* :</p>
    <p class="register_input"><input type="text" name="city"></p>
	<div class="clear"></div>
    <p class="register_text">Zip/Postal Code* :</p>
    <p class="register_input"><input type="text" name="zip"></p>
	<div class="clear"></div>
    <p class="register_text">Country* :</p>
    <p class="register_input">
    <select name="country">
    <?php foreach ($this->countrys as $country): ?>
    	<option class="country" value="<?=$country->id?>"><?=$country->name?></value>
    <?php endforeach;?>
    </select>
    </p>
	<div class="clear"></div>
    <p class="register_text">State :</p>
    <p class="register_input">
    <select name="state" id="state">
    </select></p>
	<div class="clear"></div>
    <p class="register_text">Phone* :</p>
    <p class="register_input"><input type="text" name="phone"></p>
	<div class="clear"></div>
    <p class="register_text">Mobile phone :</p>
    <p class="register_input"><input type="text" name="mobilephone"></p>
	<div class="clear"></div>
    <p class="register_text">Fax :</p>
    <p class="register_input"><input type="text" name="fax"></p>
	<div class="clear"></div>
    <p class="register_continue_button">
    	<?php // @todo если доебутся сделать нормальную кнопку ?>
     <input type="submit" value="continue">
    </p>
</form>
<?=$this->message?>
    <script>
    	$('.country').click(function(){
    		id = $(this).val();
    		 $.ajax({
			   type: "POST",
			   url: "/country/getstate/id/" + id,
			   success: function(msg){
			     $('#state').html(msg);
			   }
			 });
    	});
    </script>