<div id="checkout_stpes">
					<img src="/application/public/img/checkout_2.gif" alt="">
				</div>
				<div id="shopping_cart">
					<img src="/application/public/img/list_pencil.gif" alt="" />
					Fill in your address
				</div>
				<div id="cart_items_first_head">
					<p>Shipping Address</p>
				</div>
				<form method="post" action="<?=$this->form->getAction();?>">
				
				
				
				
				
				
					<p class="left_text"><span class="align_right">Company name : </span>
					<?=$this->form->getElement('company_s');?><span class="normal_gray">(Optional)</span></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Contact Name : </span>
					<?=$this->form->getElement('contact_s');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Address Line 1 :  </span>
					<?=$this->form->getElement('address_s');?></p>
					
					<p class="left_text"><span class="align_right">Address Line 2 :  </span>
					<?=$this->form->getElement('address2_s');?><span class="normal_gray">(Optional)</span></p>
					
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Region :  </span>
					<?=$this->form->getElement('region_s');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>State / Province :  </span>
					<?=$this->form->getElement('state_s');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>City :  </span>
					<?=$this->form->getElement('city_s');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Postal Code :  </span>
					<?=$this->form->getElement('postal_s');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Phone Number :  </span>
					<?=$this->form->getElement('phone_s');?></p>
					
					<p class="left_text"><span class="align_right">Fax Number  : </span>
					<?=$this->form->getElement('fax_s');?><span class="normal_gray">(Optional)</span></p>
						
				
											
				<div id="cart_items_first_head">
					<p>Billing Address</p>
				</div>
					<p class="text_and_check">
					<?=$this->form->getElement('shipping');?>
					<span class="bold">Same as shipping address</span> </p>
					
					<div id="hide">
					<p class="left_text"><span class="align_right">Company name : </span>
					<?=$this->form->getElement('company_b');?><span class="normal_gray">(Optional)</span></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Contact Name : </span>
					<?=$this->form->getElement('contact_b');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Address Line 1 :  </span>
					<?=$this->form->getElement('address_b');?></p>
					
					<p class="left_text"><span class="align_right">Address Line 2 :  </span>
					<?=$this->form->getElement('address2_b');?><span class="normal_gray">(Optional)</span></p>
					
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Region  :  </span>
					<?=$this->form->getElement('region_b');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>State / Province :  </span>
					<?=$this->form->getElement('state_b');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>City :  </span>
					<?=$this->form->getElement('city_b');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Postal Code :  </span>
					<?=$this->form->getElement('postal_b');?></p>
					
					<p class="left_text"><span class="align_right"><span class="red_price">*</span>Phone Number :  </span>
					<?=$this->form->getElement('phone_b');?></p>
					
					<p class="left_text"><span class="align_right">Fax Number  : </span>
					<?=$this->form->getElement('fax_b');?><span class="normal_gray">(Optional)</span></p>
					</div>
					
					<input type="submit"/>
				</form>	
				<div class="checkout_down">
					<div class="checkout_down_contain">
						<a href="/cart/">« Back</a>
						
					
						
						<img class="checkout_down_contain_button" src="/application/public/img/check_out_account_close.gif" alt="">
					
					</div>
				</div>
			
		<script>
		$(document).ready(function(){
		
		if(!$('.check').attr('checked')){
			$('#hide').show();
		} else {
			$('#hide').hide();
		}

		
		
		$('.check').click(function(){
			if(!$(this).attr('checked')){
				$('#hide').show();
			} else {
				$('#hide').hide();
			}
			//return false;
		});
	});
		</script>
		
		