<div id="main_container">
				<div id="checkout_stpes">
					<img src="/application/public/img/checkout_4.gif" alt="">
				</div>
				<div id="shopping_cart">
					<img src="/application/public/img/list_green_arrow.gif" alt="" />
					Confirm and submit your order
				</div>
				<div id="cart_items_first_head">
					<p>Address</p>
				</div>
					
				<div class="adresses">
					<p class="adresses_title"><span class="bold">Shipping to this address: </span></p>
					<p><span class="bold">Contact name: <?=$this->ship_address[0]['contact']?></span></p>
					<p>Company: <?=$this->ship_address[0]['company']?></p>
					<p>Address 1:<?=$this->ship_address[0]['address']?></p>
					<p>Address 2:<?=$this->ship_address[0]['address2']?></p>
					<p><?=$this->ship_address[0]['city']?>, <?=$this->ship_address[0]['state']?>, <?=$this->ship_address[0]['country']?></p>
					<p>Postal Code: <?=$this->ship_address[0]['postal']?> </p>
					<p>Phone: <?=$this->ship_address[0]['phone']?></p>
					<p>Fax: <?=$this->ship_address[0]['fax']?></p>
				</div>
				
				<div class="adresses">
					<p class="adresses_title"><span class="bold">Billing address: </span></p>
					<p><span class="bold">Contact name: <?=$this->bill_address[0]['contact']?></span></p>
					<p>Company: <?=$this->bill_address[0]['company']?></p>
					<p>Address 1:<?=$this->bill_address[0]['address']?></p>
					<p>Address 2:<?=$this->bill_address[0]['address2']?></p>
					<p><?=$this->bill_address[0]['city']?>, <?=$this->bill_address[0]['state']?>, <?=$this->bill_address[0]['country']?></p>
					<p>Postal Code: <?=$this->bill_address[0]['postal']?> </p>
					<p>Phone: <?=$this->bill_address[0]['phone']?></p>
					<p>Fax: <?=$this->bill_address[0]['fax']?></p>
				</div>
				
				<div class="sign_up2">
					<input type="submit" value="Modify Shipping And Billing Address">
				</div>
				<div id="cart_items_first_head">
					<p>Order 1 (seller name - dracotek)</p>
				</div>
				<div class="order">
					<p><span class="bold">Shipping method:</span> <?=$this->method['title']?> <input type="submit" value="Modify"> </p>
					<p><span class="bold">Processing Time : </span>The item(s) will be ready for shipment within <span class="bold"> 5 working days</span> after payment is received.</p>
					<div class="bucher"></div>
					<div id="cart_items_second_head">
					<p class="head_desc">Description</p>
					<p class="head_price">Price</p>
					<p class="head_quantity">Quantity</p>
					<p class="head_amount">Amount</p>
					<p class="head_buttons"></p>
				</div>
				
				

				
				<?=$this->productsInCart()?>
				
				
				<p>&nbsp;</p>
				<div class="update_quantity">

					<input class="update" value="Update Quantity" type="submit">
				</div>
				
				
				
				<div class="bucher"></div>
				<p><span class="bold">Order Summary</span></p>
				<p>Item subtotal:  	<span id="sub_price">USD <?=$this->subprice?></span></p>
				<p class="red_price bold">Order total:  	USD 418.00</p>
				</div>
				
				
				<!--
				<div id="cart_items_first_head">
					<p>Coupon</p>
				</div>
				
				<p class="coupon">Have a Coupon Code? <input class="long" type="text"> <input type="submit" value="add"></p>
				
				-->
				<div class="clear"></div>
				<div class="checkout_down">
						<h2 class="red_price h2_grand">Grand total: USD 916.99 </h2>
						<div class="clear"></div>
					<div class="checkout_down_contain">
						<a href="/order/step2/">« Back</a>
						<a class="checkout_down_contain_button" href="/order/step4/"><img src="/application/public/img/check_out_account_close.gif" alt=""></a>
					</div>
				</div
				
			</div>
			
			
			<script>
				$(document).ready(function(){

				


				
				
				$('.delete').click(function(){
					var id = $(this).attr("product_id");
					$("span[product_id='"+id+"']").html('Please wait...');
						$.ajax({
							   url: '/cart/delete/id/'+id,
							   success: function(msg){
							   	//msg ответ от сервера(будем передавать колво товаров в корзине)
								$('#cart_items_count').html(msg);
								// тут был косяк когда много товаров удаляешь
								$("span[product='"+id+"']").remove();
							   }
						});
				});
				
				$('.update').click(function(){
					var red_price = 0;
					var products_count = 0;
				
					$('input[class="count"]').each(	function(n,element){
						
						var product_count= $(element).attr('value')-0;
						var product_id = $(element).attr('product_id');	
						var product_price =$(element).attr('price');
						
						
						$.ajax({url: '/cart/update/id/'+product_id+'/count/'+product_count});
						
						
						$('p[product_id="'+product_id+'"]').html('USD '+product_count*product_price);
						red_price=red_price+product_count*product_price;
						products_count += product_count;
					});
					
										 
					$('#cart_items_count').html(products_count);
					$('span[id="sub_price"]').html('USD '+ red_price);
				});

				
				
			})
			</script>	