				

				
				
				
				
				<div id="checkout_stpes">
					<img src="/application/public/img/checkout_5.gif" alt="">
				</div>
				<div id="sucsess_register">
					<img src="/application/public/img/check_out_new_success_bg.gif" alt="">
					<p class="big_orange">Your order has been placed successfully.</p>
					<p><span class="bold">Order number is: #0903148652 </span></p>
					<h2 class="red_price">Grand total:  	USD 344.85</h2>
				</div>
				<div class="payment_change">
					<p><span>Pay your order via</span></p>
					
				
<?php foreach ($this->payments as $method):?>

<p>
<input type="radio" id="<?=$method['id']?>" class="payment" name="group">
<?php if($method['image']):?>
<img alt="" src="/application/public/images/payment/<?=$method['image']?>"> 
<?php endif?>
<?=$method['title']?>
</p>

<p><?=$method['about']?></p>
</input>
</p>

<?php endforeach;?>
					
					
				
				
				</div>
				<span class="hide">
				<div class="payment_button">
					<a href="#"><img src="/application/public/img/check_out_new_btn1.gif" alt=""></a>
				</div>
				</span>
				<p id="wait" class="bold">  Please wait ...  </p>
					
<script>
		$('.hide').hide();
		$('#wait').hide();
		$('.payment').click(function(){
			
		var id = $(this).attr('id');
		$('.hide').hide();
		$('#wait').show();
			
		$.ajax({
			   type: "POST",
			   url: "/order/setpayment/id/"+id,
			   success: function(msg){
				
			$('.hide').show();
				$('#wait').hide(); 		
						//window.location.href = '/order/step2/'
				 }
			 });
		})
		
		</script>