<?php if($_SESSION['admin']):?>
<?=$this->form?>
<?php endif?>

<?php foreach ($this->methods as $method):?>

<div>

<input type="radio" id="<?=$method['id']?>" class="shipping"  name="group">
<?php if($method['image']):?>
<img alt="" src="/application/public/images/shipping/<?=$method['image']?>">
<?php endif?>
<p><?=$method['title']?></p>
<p><?=$method['about']?></p>
</input>
</div>

<?php endforeach;?>



		
<div class="checkout_down">
	<div class="checkout_down_contain">
	
	
		
		<a href="/order/step1/">« Back</a>
		<span class="hide">
		<a href="/order/step3/"><img class="checkout_down_contain_button" src="/application/public/img/check_out_account_close.gif" alt="">
		</a>
		</span>
		<p id="wait" class="bold">  Please wait ...  </p>
	</div>
</div>


<script>
		$('.hide').hide();
		$('#wait').hide();
		$('.shipping').click(function(){
			
		var id = $(this).attr('id');
		$('.hide').hide();
		$('#wait').show();
			
		$.ajax({
			   type: "POST",
			   url: "/order/setmethod/id/"+id,
			   success: function(msg){
				$('.hide').show();
				$('#wait').hide(); 		
						//window.location.href = '/order/step2/'
				 }
			 });
		})
		
		</script>