<div id="checkout_stpes">
					<img src="/application/public/img/checkout_2.gif" alt="">
				</div>
				<div id="shopping_cart">
					<img src="/application/public/img/list_pencil.gif" alt="" />
					Fill in your address
				</div>
				<div id="cart_items_first_head">
					<p>Shipping Address</p>
				</div>
				<form action="<?=$this->form->getAction()?>" method="POST" class="shipping">
								<p class="left_text"><span class="align_right">Company name : </span><?=$this->form->company?><span class="normal_gray">(Optional)</span></p>
								<p class="left_text"><span class="align_right"><span class="red_price">*</span>Contact Name : </span><?=$this->form->contact?></p>
								<p class="left_text"><span class="align_right"><span class="red_price">*</span>Address Line 1 :  </span><?=$this->form->address?></p>
								<p class="left_text"><span class="align_right"><span class="red_price">*</span>Address Line 2 :  </span><?=$this->form->address2?><span class="normal_gray">(Optional)</span></p>
								<p class="left_text"><span class="align_right"><span class="red_price">*</span>City :  </span><?=$this->form->city?></p>
								<p class="left_text"><span class="align_right"><span class="red_price">*</span>State / Province :  </span><?=$this->form->state?></p>
								<p class="left_text"><span class="align_right"><span class="red_price">*</span>Country :  </span><?=$this->form->country?></p>
								<p class="left_text"><span class="align_right"><span class="red_price">*</span>Postal Code :  </span><?=$this->form->postal?></p>
								<p class="left_text"><span class="align_right"><span class="red_price">*</span>Phone Number :  </span><?=$this->form->phone?></p>
								<p class="left_text"><span class="align_right">Fax Number  : </span><?=$this->form->fax?><span class="normal_gray">(Optional)</span></p>
								<p><span class="align_right"><?=$this->form->submit?></span></p>
				</form>
				<div id="cart_items_first_head">
					<p>Billing Address</p>
				</div>
					<p class="text_and_check">
					<input type="checkbox" class="check" checked > <span class="bold">Same as shipping address</span> </p>
					<form action="<?=$this->form->getAction()?>" method="POST" class="billing">
					</form>
				<div class="checkout_down">
					<div class="checkout_down_contain">
						<a href="/cart/">« Back</a>
						
					<p id="wait" class="bold">   Please wait ...</p>
						<span id="hide">
						<img class="checkout_down_contain_button" src="/application/public/img/check_out_account_close.gif" alt="">
						</span>
					</div>
				</div>
			
		<script>
		$('#wait').hide();
		$('.checkout_down_contain_button').click(function(){
			$('#wait').show();
			$('#hide').hide();
			data = $('.shipping').serialize();
			$.ajax({
			   type: "POST",
			   url: "/adress/add/shipping/1/",
			   data: data,
			   success: function(msg){
			     		data = $('.billing').serialize();
			     		
						$.ajax({
						   type: "POST",
						   url: "/adress/add/shipping/0/",
						   data: data,
						   success: function(msg){
						     	window.location.href = '/order/step2/'
						   }
						 });
			   }
			 });
		})
		$('.check').click(function(){
			if(!$(this).attr('checked')){
				$('.shipping').clone(true).attr('class', 'billing').replaceAll('.billing');
			} else {
				$('.billing').html(' ');
			}
			//return false;
		});
		</script>
		
		