<div id="main_container">
				<div id="checkout_stpes">
					<img src="/application/public/img/checkout_4.gif" alt="">
				</div>
				<div id="shopping_cart">
					<img src="/application/public/img/list_green_arrow.gif" alt="" />
					Confirm and submit your order
				</div>
				<div id="cart_items_first_head">
					<p>Address</p>
				</div>
					
				<div class="adresses">
					<p class="adresses_title"><span class="bold">Shipping to this address: </span></p>
					<p><span class="bold">Contact name: <?=$this->ship_address['contact']?></span></p>
					<p>Company: <?=$this->ship_address['company']?></p>
					<p>Address 1:<?=$this->ship_address['address']?></p>
					<p>Address 2:<?=$this->ship_address['address2']?></p>
					<p><?=$this->ship_address['city']?>, <?=$this->ship_address['state']?>, <?=$this->region2['name']?></p>
					<p>Postal Code: <?=$this->ship_address['postal']?> </p>
					<p>Phone: <?=$this->ship_address['phone']?></p>
					<p>Fax: <?=$this->ship_address['fax']?></p>
				</div>
				
				<div class="adresses">
					<p class="adresses_title"><span class="bold">Billing address: </span></p>
					<p><span class="bold">Contact name: <?=$this->bill_address['contact']?></span></p>
					<p>Company: <?=$this->bill_address['company']?></p>
					<p>Address 1:<?=$this->bill_address['address']?></p>
					<p>Address 2:<?=$this->bill_address['address2']?></p>
					<p><?=$this->bill_address['city']?>, <?=$this->bill_address['state']?>, <?=$this->region1['name']?></p>
					<p>Postal Code: <?=$this->bill_address['postal']?> </p>
					<p>Phone: <?=$this->bill_address['phone']?></p>
					<p>Fax: <?=$this->bill_address['fax']?></p>
				</div>
				
				<div class="sign_up2">
					<form action="/order/step1/modify/1/">
					<input type="submit" value="Modify Shipping And Billing Address">
					</form>
				</div>
				<div id="cart_items_first_head">
					<p>Shipping</p>
				</div>
				<div class="order">
					<form action="/order/step2/">
					<span class="bold">Shipping method:</span> <?=$this->method['title']?> 
					
					<input type="submit" value="Modify"> 
					</form>
					<p><span class="bold">Processing Time : </span>The item(s) will be ready for shipment within <span class="bold"> 5 working days</span> after payment is received.</p>
					<div class="bucher"></div>
					<div id="cart_items_second_head">
					<p class="head_desc">Description</p>
					<p class="head_price">Price</p>
					<p class="head_quantity">Quantity</p>
					<p class="head_amount">Amount</p>
					<p class="head_buttons"></p>
				</div>
				
				

				
				<?=$this->productsInCart()?>
				
				
				<p>&nbsp;</p>
				<div class="update_quantity">

					<input class="update" value="Update Quantity" type="submit">
				</div>
				
				
				
				<div class="bucher"></div>
				<p><span class="bold">Order Summary</span></p>
				<p>Item subtotal: <span id="sub_price"><?=$this->valute($this->subprice,2)?></span></p>
				<p class="bold">Shipping total: <?=$this->valute(1,3)?> <span id="shipping_total"><?=$this->valute($this->shipping_price,0)?></span></p>
				<p class="red_price bold">Order total: <?=$this->valute(1,3)?> <span id="order_total"><?=$this->valute($this->grandtotal,0)?></span></p>
				
				</div>
				
				
				<!--
				<div id="cart_items_first_head">
					<p>Coupon</p>
				</div>
				
				<p class="coupon">Have a Coupon Code? <input class="long" type="text"> <input type="submit" value="add"></p>
				
				-->
				<div class="clear"></div>
				<div class="checkout_down">
						<h2 class="red_price h2_grand">Grand total: <?=$this->valute(1,3)?> <span id="grand_total"><?=$this->valute($this->grandtotal,0)?></span> </h2>
						<div class="clear"></div>
					<div class="checkout_down_contain">
						<a href="/order/step2/">« Back</a>
						<a class="checkout_down_contain_button" href="/order/step3/confirm/1/"><img src="/application/public/img/check_out_new_btn2.gif" alt=""></a>
					</div>
				</div>
				
			</div>
			
			
			<script>
				$(document).ready(function(){

				


				
				
				$('.delete').click(function(){
					var id = $(this).attr("product_id");
					$("span[product_id='"+id+"']").html('Please wait...');
						$.ajax({
							   url: '/cart/delete/id/'+id,
							   success: function(msg){
							   	//msg ответ от сервера(будем передавать колво товаров в корзине)
								$('#cart_items_count').html(msg);
								// тут был косяк когда много товаров удаляешь
								$("span[product='"+id+"']").remove();
							   }
						});
				});
				
				$('.update').click(function(){
					var red_price = 0;
					var products_count = 0;
					var arr={};
					var shipping_price = 0
					var regionCoef=<?=$this->region_coef?>;
					var shippingCoef=<?=$this->method['coef']?>;
					
					$('input[class="count"]').each(	

						
						function(n,element){
						
						var product_count= $(element).attr('value')-0;
						var product_id = $(element).attr('product_id');	
						var product_price =$(element).attr('price');
						var product_category = $(element).attr('category');

						if(!product_count){
							product_count=0;
						}
						
						if(product_count<1){
							product_count=0;
						}
						$.ajax({url: '/cart/update/id/'+product_id+'/count/'+product_count});

						if(product_count==0){
						$("span[product='"+product_id+"']").remove();
						}
						if(!arr[product_category]){
							arr[product_category]=0;}
							arr[product_category]+= (product_count-0);

							shipping_price=0;
							for(var i in arr) {
							    if (!arr.hasOwnProperty(i)) {continue;}
							  if(arr[i]>0){
								var categoryCoef=$('input[category="'+i+'"]').attr('coef'); 
							
							    shipping_price+=(arr[i]*0.1+1)*30*categoryCoef*regionCoef*shippingCoef*<?=$this->valute(1,0)?>;}
							    
							   	}
																
				
						
						
						$('p[product_id="'+product_id+'"]').html('<?=$this->valute(1,3)?> '+product_count*product_price);
						red_price=red_price+product_count*product_price;
						products_count += product_count;
					}

						
						);
				

					
					
					$('#cart_items_count').html(products_count);
					$('span[id="sub_price"]').html('<?=$this->valute(1,3)?> '+ Math.ceil(red_price*100)/100);
					$('#order_total').html(Math.ceil((shipping_price+red_price)*100)/100);
					$('#shipping_total').html(Math.ceil(shipping_price*100)/100);
					$('#grand_total').html(Math.ceil((shipping_price+red_price)*100)/100);
				});

				
				
			})
			</script>	