				
<?php if($_SESSION['admin']):?>
<?=$this->form?>
<?php endif?>
				
				
				
				
				<div id="checkout_stpes">
					<img src="/application/public/img/checkout_5.gif" alt="">
				</div>
				<div id="sucsess_register">
					<img src="/application/public/img/check_out_new_success_bg.gif" alt="">
					<p class="big_orange">Your order has been placed successfully.</p>
					<p><span class="bold">Order number is: #0903148652 </span></p>
					<h2 class="red_price">Grand total:  	USD 344.85</h2>
				</div>
				<div class="payment_change">
					<p><span>Pay your order via</span></p>
					
				
<?php foreach ($this->payments as $method):?>

<p>

<input type="radio" id="<?=$method['id']?>" name="group">
<?=$method['title']?>
<?php if($method['image']):?>
<img alt="" src="/application/public/images/payment/<?=$method['image']?>"> 
<?php endif?>
<?php if($_SESSION['admin']):?>
<a href="/order/paymentdelete/id/<?=$method['id']?>"> delete</a>
<?php endif?>
</p>

<p><?=$method['about']?></p>
</input>
</p>

<?php endforeach;?>
					
					
				
				
				</div>
				<div class="payment_button">
					<a href="#"><img src="/application/public/img/check_out_new_btn1.gif" alt=""></a>