		<div id="footer">
				<img src="/application/public/img/foot_help_tbg.gif" alt="">
				<div id="china_footer_content">
					<div id="title_china_footer_content">The Leader in China Wholesale</div>
					<p>
						DHgate.com is a leading <span class="bold"> China wholesale </span>
						fast trading marketplace serving global buyers since 2004. As PayPal's
						 largest client in the Asia-Pacific region, 
						 DHgate offers over 10 million high quality wholesale products from more 
						 than 100,000 dedicated<span class="bold"> Chinese wholesalers </span>
						 and manufactuerers. Our Escrow payment processes and fast global delivery 
						 guarantee you a great China wholesale shopping experience.
					</p>
				</div>
				<img src="/application/public/img/foot_help_bbg.gif" alt="">
				<div class="bucher"></div>
				<img src="/application/public/img/foot_help_tbg.gif" alt="">
				<div id="china_ul_content">
					<div class="ul_content">
						<ul>
							<span>Pamyment</span>
								<li><a href="#">Escrow</a></li>
								<li><a href="#">Payment Methods</a></li>
								<li><a href="#">Payment Confirmation</a></li>
						</ul>
					</div>
					<div class="ul_content">
						<ul>
							<span>Shipment</span>
								<li><a href="#">Shipping Methods</a></li>
								<li><a href="#">Shipping Cost Calculation</a></li>
								<li><a href="#">Order Tracking</a></li>
								<li><a href="#">Customs</a></li>
						</ul>
					</div>
					<div class="ul_content">
						<ul>
							<span>Dispute</span>
								<li><a href="#">Dispute Process</a></li>
								<li><a href="#">Escalated Disputes</a></li>
						</ul>
					</div>
					<div class="ul_content">
						<ul>
							<span>Customer Service</span>
								<li><a href="#">Help</a></li>
								<li><a href="#">Contact Customer Service</a></li>
						</ul>
					</div>
				</div>
				<img src="/application/public/img/foot_help_bbg.gif" alt="">
				<div class="bucher"></div>
				<div id="down_href_bar">
					<a href="#"> Home </a> |
					<a href="#"> Your Account </a> |
					<a href="#"> Help </a> |
					<a href="#"> Top Products </a> |
					<a href="#"> About Us </a> |
					<a href="#"> Contact Us </a> |
					<a href="#"> Security & Privacy </a> |
					<a href="#"> Terms of Use </a> |
					<a href="#"> Affiliates </a> 
				</div>
				<div id="down_image_bar">
					<img src="/application/public/img/footer_0002.gif" alt="plastic cards">
					<a href="#"><img src="/application/public/img/footer_02_001.gif" alt="PayPall"></a>
					<a href="#"><img src="/application/public/img/footer_01.gif" alt="Secured"></a>
					<a href="#"><img src="/application/public/img/footer_ups.gif" alt="UPS"></a>
					<p>Copyright Notice © 2004 - 2009 DHgate.com All rights reserved.</p>
				</div>
			</div>