			<div id="first_level_header">
				<a href="#"><img class="logo" src="/application/public/img/dhgatelo.gif" alt="logo"></a>
				<div id="advertis">Fast Trading Marketplace</div>
				<div id="header_up_menu">
					<a href="#"> Sign In </a> |
					<a href="#"> Join Free </a> | 
					<a href="#"> Help </a> 
				</div>
			
				<div class="clear"></div>
			
				<div id="menu_button_right"><a href="#">Contact Us</a></div>
				<div id="menu_button_middle"><a href="#">About Us</a></div>
				<div id="menu_button_left"><a href="#">Home</a></div>
				
				<div class="clear"></div>
				
				<div id="search_pannel">
					<img class="search_pannel_left" src="/application/public/img/search_pannel_left.gif" alt="">
					<form action="#">
						<div id="text_search">Search</div>
						<input type="text">
						<select>
							<option>All_categories</option>
						</select>
						<div class="go_button"><a href="#"></a></div>
					</form>
					<img class="search_pannel_right" src="/application/public/img/search_pannel_right.gif" alt="">
					<div class="cart_button"><a href="#">Cart 0 <span>item(s)</span></a></div>
					
					<div class="clear"></div>
					
					<div id="head_down_menu">
						<img class="search_pannel_left" src="/application/public/img/head_down_menu_left.gif" alt="">
						<div class="all_categories">
							<a href="#">All categories</a>
							<img class="arrow" src="/application/public/img/small_arrow.gif" alt="">
						</div>
						<img class="search_pannel_left" src="/application/public/img/vertical_line.gif" alt="">
						<a href="#">Special Offer</a>
						<img class="search_pannel_left" src="/application/public/img/vertical_line.gif" alt="">
						<a href="#">Wat's New</a>
						<img class="search_pannel_left" src="/application/public/img/vertical_line.gif" alt="">
						<a href="#">Order Tracking</a>
						<img class="search_pannel_left" src="/application/public/img/vertical_line.gif" alt="">
						<img class="search_pannel_right" src="/application/public/img/head_down_menu_right.gif" alt="">
					</div>
				</div>
			</div>
			<div class="clear"></div>
		<div class="all_categories_container">
			<?=$this->categoryTop();?>
			<div class="clear"></div>
			<img src="/application/public/img/all_bg0.gif" alt="">
		</div>