<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style>
#screenshot{
    position:absolute;
    border:1px solid #ccc;
    background:#333;
    padding:1px;
    display:none;
    color:#fff;
    /* text-align:left; */
}
</style>

<link rel="stylesheet" type="text/css"
	href="/application/public/css/style.css">

<title>Wholesale - Buy China Wholesale Products from Chinese Wholesalers
on DHgate.com</title>
<script language="javascript" type="text/javascript"
	src="/application/public/js/jquery-1.3.2.min.js"></script>
<script language="javascript" type="text/javascript"
	src="/application/public/js/jquery-ui-1.7.2.custom.min.js"></script>
<script language="javascript" type="text/javascript"
	src="/application/public/js/ocupload.js"></script>

<script language="javascript" type="text/javascript"
	src="/application/public/js/main.js"></script>
		


<script language="JavaScript" type="text/javascript">
			$(document).ready(function(){
						$(".all_categories_container").hide();
						$(".all_categories").hover(function() {
							$(".all_categories_container").hover(function() {
								$(this).show();
								$(".all_categories").addClass('hover_button');
							}, function() {
								$(".all_categories_container").hide();
								$(".all_categories").removeClass('hover_button');
							})
							$(".all_categories_container").show();
							}, function() {
								$(".all_categories_container").hide();
								$(".all_categories").removeClass('hover_button');
								});
						});	
		</script>
		


	
</head>
<body>
<div id="bhgate_site"><?=$this->render('header.phtml')?>
<div id="main_container"><?php $request = Zend_Controller_Front::getInstance()->getRequest();
if($request->getControllerName() != 'user'):
if($request->getControllerName() != 'cart'):
if(($request->getControllerName() != 'product') or ($request->getActionName()=='search')):
if($request->getControllerName() != 'admin'):
if($request->getControllerName() != 'order'):
if($request->getActionName() != 'category'):
if(($request->getControllerName() !='catalog' )and
$request->getActionName() != 'view'):
?> <?=$this->render('left.phtml')?>
<div id="center_container">
<?php endif;?> 
<?php endif;?> 
<?php endif;?> 
<?php endif;?>
<?php endif;?>
<?php endif;?> 
<?php endif;?> 
<?=$this->layout()->content?> 
<?php
if($request->getControllerName() != 'admin'):
if($request->getActionName() != 'help' and $request->getControllerName() == 'index'):
if($request->getActionName() != 'about' and $request->getControllerName() == 'index'):
if($request->getActionName() != 'contact' and $request->getControllerName() == 'index'):
if($request->getControllerName() != 'user'):
if($request->getControllerName() != 'cart'):
if($request->getControllerName() != 'order'):
if($request->getActionName() != 'category' && $request->getControllerName() != 'product'):
if(($request->getControllerName() !='catalog' )and $request->getActionName() != 'view'):
?>
</div>
<?=$this->render('right.phtml')?>

<?php endif;?>
<?php endif;?>
<?php endif;?>
<?php endif;?>
<?php endif;?>
<?php endif;?>
<?php endif;?>
<?php endif;?>
<?php endif;?></div>
<div class="clear"></div>
<?=$this->render('footer.phtml')?></div>
</body>
</html>
