				<div id="left_container">
					<div class="title_left_menu_gray">Categories</div>
					<ul>
					<?=$this->categorys()?>
					<!--
						<li class="title_left_menu">
						 <a href="#">Name Category <img class="arrows" src="/application/public/img/arrows-ffffff.gif"></a>
							<ul class="right_fall_list">
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
							</ul>
						</li>
						<li class="title_left_menu"><a href="#">Name Category</a>
							<ul class="right_fall_list">
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
							</ul>
						</li>
						<li class="title_left_menu"><a href="#">Name Category</a>
							<ul class="right_fall_list">
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
							</ul>
						</li>
						<li class="title_left_menu"><a href="#">Name Category</a>
							<ul class="right_fall_list">
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
							</ul>
						</li>
						<li class="title_left_menu"><a href="#">Name Category</a>
							<ul class="right_fall_list">
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
								<li class="items_title"><a href="#">Item</a></li>
							</ul>
						</li>
					--></ul>
					<form class="admin_form_add_category" method="post" action="/catalog/add/parent_id/<?=$this->current_category_id?>">
						<p>
							<input type="text" name="title"/>
						</p>
						<p>
							<input type="submit" value="add"/>
						</p>
					</form>
					<img class="left_banner" src="/application/public/img/left_ban.gif" alt="">
						<div class="head_left_block">Wholesale Searches</div>
						<div class="left_block_contain"></div>
						<div class="left_block_down"></div>
						<div class="head_left_block">Success Stories</div>
						<div class="left_block_contain">
							<p>
							<img src="/application/public/img/person00.jpg" alt="">
							At first, I bought 2 mobile phones for myself and my husband from eBay.
							I decided to sell them to other people since my husband couldn't use it when
							he switched to a different network. A lot of people replied to my ad…
							</p>
							<div class="client_name">----<a href="#"> Cherrie Thompson</a></div>
							<div class="more_clients"><a href="#">More Success Stories »</a></div>
						</div>
						<div class="left_block_down"></div>
					</div>