Results&nbsp;
<?=$this->firstItemNumber-1?>
&nbsp;-&nbsp;
<?=$this->firstItemNumber+$this->currentItemCount-1?>
&nbsp;of&nbsp;
<?=$this->totalItemCount?>
<?php
if ((!($this->pageCount<=1))){ ?>
<a href="<?= $this->url(array('page' =>$this->current-1)); ?>">« Prev</a>
<?php
if($this->first == $this->current){?>
<span class="paginator_active_page"><?=$this->first?></span>
<?}else {?>
<a href="<?= $this->url(array('page' =>$this->first)); ?>"><?= $this->first ?></a>

<?php
}
if ($this->current >=$this->first+3){?>
<a href="<?= $this->url(array('page' =>$this->previous-1)); ?>">...</a>

<?
}
if (($this->current!=$this->first+1)&&($this->previous <> '')){
	?>
<a href="<?= $this->url(array('page' =>$this->previous));?>"><?=$this->previous?></a>

	<?}
	if($this->first != $this->current){
		?>
<span class="paginator_active_page"><?=$this->current?></span>
		<?}
		if ($this->current != $this->last-1){
			?>
				<a href="<?= $this->url(array('page' =>$this->next)); ?>"><?=$this->next?></a>

			<?

		}
		if ($this->current <=$this->last-3){?>
<a href="<?= $this->url(array('page' =>$this->next+1)); ?>">...</a>
		<?
		}
		if($this->last != $this->current){?>
			<a href="<?= $this->url(array('page' =>$this->last)); ?>"><?= $this->last ?></a>
		<?php }?>
			<a href="<?= $this->url(array('page' =>$this->current+1));?>">Next »</a>
		<?php }?> 
