



<?php if ($this->pageCount > 1): ?>
<div id="paginationControl">

Results
<?=$this->firstItemNumber?>
&nbsp;-
<?=$this->firstItemNumber+$this->currentItemCount-1?>
&nbsp;of
<?=$this->totalItemCount?>

Page&nbsp;
<?=$this->current?>
&nbsp;of&nbsp;
<?=$this->pageCount?>


<!-- Первая страница -->

<?php if (isset($this->previous)): ?>
  <a href="<?= $this->url(array('page' => $this->first)); ?>">First</a>
<?php else: ?>
  <a href="#first">First</a>
 <?php endif; ?>

<!-- Предыдущая страница -->
<?php if (isset($this->previous)): ?>
  <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Prev</a> 
<?php else: ?>
  <a href="#prev">&lt; Prev</a>
<?php endif; ?>

<!-- Ссылки на страницы -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
  <?php else: ?>
    <span class="paginator_active_page"><?= $page; ?></span> 
  <?php endif; ?>
<?php endforeach; ?>

<!-- Следующая страница -->
<?php if (isset($this->next)): ?>
  <a href="<?= $this->url(array('page' => $this->next)); ?>">Next &gt;</a>
<?php else: ?>
  <a href="#next">Next &gt;</a>
<?php endif; ?>

<!-- Последнюю страница -->
<?php if (isset($this->next)): ?>
  <a href="<?= $this->url(array('page' => $this->last)); ?>">Last</a>
<?php else: ?>
  <a href="#last">Last</a>
<?php endif; ?>



</div>
<?php endif; ?>


