
<div id="right_container"><a href="#"><img
	src="/application/public/img/escrow_n.gif" alt=""></a>
<div class="clear"></div>
<div id="sign_in">
<?php if(!Zend_Auth::getInstance()->hasIdentity()):?>
<div id="please_sign_in">Please <a href="/user/login/"> Sign In</a></div>

<!-- <div id="watch_our"><a href="#">Watch Our Info Clip</a></div> -->

<div id="button_join_free"><a href="/user/register/"></a></div>
<?php else:?>
<div id="please_sign_in"><h3>Hello, <?=Zend_Auth::getInstance()->getIdentity()->login ?></h3></div>
<h4><a href="/user/">Go To Your Profile</a></h4>
<?php endif;?>
</div>
<div id="hot_deals_up">Hot Deals</div>
<div id="hot_deals_content">
<div class="hot_deals_title"><img
	src="/application/public/img/01000000.jpg" alt=""> <a href="#">FURminator
DeShedding Tools</a>
<p>$6.74/piece</p>
</div>
<div class="hot_deals_title"><img
	src="/application/public/img/01000000.jpg" alt=""> <a href="#">FURminator
DeShedding Tools</a>
<p>$6.74/piece</p>
</div>
<div class="hot_deals_title"><img
	src="/application/public/img/01000000.jpg" alt=""> <a href="#">FURminator
DeShedding Tools</a>
<p>$6.74/piece</p>
</div>
<div class="hot_deals_title"><img
	src="/application/public/img/01000000.jpg" alt=""> <a href="#">FURminator
DeShedding Tools</a>
<p>$6.74/piece</p>
</div>
<div class="clear"></div>
</div>
<img class="hot_deals_down"
	src="/application/public/img/right_bottom_bg.gif" alt="">
<div class="clear"></div>
<img class="we_ship" src="/application/public/img/ban_ups0.gif" alt="">
</div>
