
<?php
$navigate = array(
array('href'=>'/catalog/view/', 'text'=>'Catalog'),
);
if($this->currentCategory){
	if($this->parent){
		array_push($navigate, array('href'=>'/catalog/category/id/'.$this->parent->id, 'text'=>$this->parent->title));
	}
	array_push($navigate, array('href'=>'/catalog/category/id/'.$this->currentCategory->id, 'text'=>$this->currentCategory->title));
	array_push($navigate, array('href'=>'', 'text'=>'New product'));
}

?>

<?=$this->navigate($navigate)?>



<?=$this->form?>
