



<!--     <form class="profuct_add_form" action="/product/add/category/<?//=$this->category?>" method="post">
          <p>Title:</p>
          <p><input type="text" name="title"></p>
		  <div class="clear"></div>
          <p>Price:</p>
          <p><input type="text" name="price"></p>
		  <div class="clear"></div>
          <p>Old Price:</p>
          <p><input type="text" name="oldprice"></p>
		  <div class="clear"></div>
         <p>Short about:</p>
          <p><textarea rows="5" cols="20" name="short_about"></textarea></p>
		  <div class="clear"></div>
          <p>About:</p>
          <p><textarea rows="5" cols="20" name="about"></textarea></p>
		  <div class="clear"></div>
          <p>Specification:</p>
          <p><textarea rows="5" cols="20" name="specifications"></textarea></p>
		  <div class="clear"></div>
          <p><input type="submit" value="Add Product"></p>
     </form>  
     -->

<p>Текущая категория : <a
	href="/catalog/category/id/<?=$this->currentCategory->id?>"><?=$this->currentCategory->title ?></a></p>
<?=$this->form?>
