
<?php
$navigate = array(
array('href'=>'/catalog/view/', 'text'=>'Catalog'),
);
if($this->category){
	if($this->parent){
		array_push($navigate, array('href'=>'/catalog/category/id/'.$this->parent->id, 'text'=>$this->parent->title));
	}
	array_push($navigate, array('href'=>'/catalog/category/id/'.$this->category[0]['id'], 'text'=>$this->category[0]['title']));
	array_push($navigate, array('href'=>'', 'text'=>$this->product->title));
}

?>

<?=$this->navigate($navigate)?>


<?php echo $this->form;?>