<a href="/">Home</a> >
<a href="/catalog/">Cataog</a> >
<?php if(isset($this->parents[0]->id)):?>
<a href="/catalog/category/id/<?=$this->parents[0]->id?>"><?=$this->parents[0]->title?></a> > 
<?php endif?>
<a href="/catalog/category/id/<?=$this->category[0]['id']?>"><?=$this->category[0]['title']?></a> >
<?=$this->product->title?>
<p>&nbsp;</p>

<div id="item_description"><img class="up_border"
	src="/application/public/img/Item_border_up.gif" alt="">
<div id="item_description_contain">
<p class="img_container">
<?php if($_SESSION['admin']):?>
<a href="#" id="upload">upload</a>
<?php endif?>

<script type="text/javascript">
		$('#upload').upload({
		       name: 'file',
		       method: 'post',
		       enctype: 'multipart/form-data',
		       action: '/product/upload/id/' + '<?=$this->product->id?>',
		       onComplete: function(data) {
				$.ajax({
					   url: '/product/getimage/id/<?=$this->product->id?>',
					   success: function(msg){
							
							$('#main_image').html(msg);
					
															
							
					   }
				});
		       }
		});
	</script>
<span id=main_image>
<img id=test src="<?php echo $this->image?>" alt=""><a href="#"></a>
</span>
</p>

<div id="item_details">
<?php if($_SESSION['admin']):?>
<p> <?=$this->moveProduct($this->product->id)?></p>
 <?php endif;?>
<h1><?=$this->product->title?></h1>
<table class="item_detail_table">
	<tr>
		<td class="left_td">Unit Price:</td>
		<td class="right_td"><span class="red_price bold">USD <?=$this->product->price?>
	</span></td>
	</tr>
	<tr>
		<td class="left_td"></td>
		<td class="right_td"><a href="#">Change Currency <img
			src="/application/public/img/ico_select.gif" alt=""></a></td>
	</tr>
	<tr>
		<!--<td class="left_td">Options:</td>
		<td class="right_td"><select>
			sdf
		</select></td>
	--></tr>
	<tr>
		<td class="left_td">Wholesale Price:</td>
		<td class="right_td">24 items per Lot</td>
	</tr>
	<tr>
		<td class="left_td"></td>
		<td class="right_td">
		<table class="items_detail_table_small">
			<tr class="gray_tr">
				<td>Quantity(lots)</td>
				<td>Price(per lot)</td>
				<!--<td><a href="#">Detail</a></td>
			--></tr>
			<tr>
				<td>1 --- 10</td>
				<td>USD 236.10</td><!--
				<td><a href="#">Detail</a></td>
			--></tr>
		</table>
		</td>
	</tr>
	<tr>
		<td class="left_td">Shipping Cost:</td>
		<td class="right_td"><span class="bold">USD 219.77</span> to <a
			href="#">Russia via EMS <img
			src="/application/public/img/ico_select.gif" alt=""></a></td>
	</tr>
</table>
<table class="yellow_table">
	<tr>
		<td>Purchase Quantity</td>
		<td><input type="text"> Lot</td>
	</tr>
	<tr>
		<td></td>
		<td>236.1 × 1 + 219.77 = <span class="red_price bold">455.87</span>
		(USD)</td>
	</tr>
	<tr>
		<td></td>
		<td>
		
		<div product_id="<?=$this->product->id?>">
		<?php if(!$this->cart->isProductInCart($this->product->id)):?>
		<a class="add_to_card"  id="<?=$this->product->id?>" href="#add">
		<img src="/application/public/img/addtocart.gif" alt="">
		</a>
		<?php else:?>
		Already in your cart
		<?php endif?>
		</div>
		
		
		
</td>
	</tr>
</table>

<!--
<table class="item_detail_table">
	<tr>
		<td class="left_td">Time Left:</td>
		<td class="right_td">27 days 8 hours</td>
	</tr>
	<tr>
		<td class="left_td">Payment:</td>
		<td class="right_td">PayPal, VISA, West Union <a href="#">Detail</a></td>
	</tr>
</table>
-->
</div>
</div>

<img class="down_border"
	src="/application/public/img/Item_border_down.gif" alt=""></div>

<div id="item_description_container">
<div id="head_item_description"><img class="desc_top"
	src="/application/public/img/description_tab.gif" alt=""></div>
<img class="description_border_up"
	src="/application/public/img/desc_up.gif">
<div id="cover_description_table"><!--Табличка с полным описанием товара, по задумке хавается из базы -->
<?=$this->product->about?> 
</div>
<img class="description_border_up"
	src="/application/public/img/desc_down.gif"></div>
<script
	type="text/javascript" src="/application/public/js/ocupload.js"></script>
	
<script>
			$(document).ready(function(){
				$('.add_to_card').click(function(){
					var id = $(this).attr("id");
					$("div[product_id='"+id+"']").html('Please wait...');
						$.ajax({
							   url: '/cart/add/id/'+id,
							   success: function(msg){
							   	//msg ответ от сервера(будем передавать колво товаров в корзине)
								$('#cart_items_count').html(msg);
								$("div[product_id='"+id+"']").html('Added To Cart');
							   }
						});
					});
				
			})
			</script>	
