
<div class="line_center_container"></div>
<div id="head_center_container">
<div id="contain_head_center_container">
<div id="right_contain_head_center_container"></div>
<div id="left_contain_head_center_container"><a href="/">Home</a> >
Search</div>
</div>
</div>


<div id="right_product_frame">
<div id="right_product_frame_up_bar">Results</div>
<div id="right_product_frame_contain">

<div id="info_found_items"> 
Your Search Text is  "<span class="bold"><?=$this->textsearch?></span>" in  <span class="bold"> 
<?=$this->category_title?>;	</span>
Number of items found:  <span class="bold"> <?=$this->products->getTotalItemCount();?></span>
</div>

<div class="clear"></div>


<div id="Items_per_page">
Items per page:
<?php if($this->count != 20):?> 
<a href="#20" class='count'>20</a> 
<?php else :?>
 <span>20</span> 
 <?php endif?> | <?php if($this->count != 40):?>
<a href="#40" class='count'>40</a> 
<?php else :?> 
<span>40</span> 
<?php endif?>
</div>
<div class="paginator"><?=$this->paginationControl($this->products, 'Sliding', 'my_pagination.phtml'); ?>

</div>
<!-- Начало блока с товаром --> 
<?php if(count($this->products)):?> <?php foreach($this->products as $product):?>
<?php if($this->image):?>
<div class="product_gallery_unit"><img
	src="<?=$this->imageSmall($product['id'])?>" alt="">
<p><a href="#"><img src="/application/public/img/loadimage_bg2.gif"
	alt=""> Enlarge</a></p>
<a href="/product/index/id/<?=$product['id']?>"><?=$product['title']?></a>
<span>$ <?=$product['price']?> </span> 







<div class="add_to_card_button" id="<?=$product['id']?>" ></div>





</div>

<?php else:?>
<div class="product_list_unit">
<div class="product_list_unit_image">

<img src="<?=$this->imageSmall($product['id'])?>" alt="">

</div>
<div class="product_list_unit_about"><a
	href="/product/index/id/<?=$product['id']?>"><?=$product['title']?> </a>
<p><?=$product['short_about']?></p>
<span></span>

<p><a href="#"><img src="/application/public/img/loadimage_bg2.gif" alt=""> Enlarge</a></p>
	
	<?php if ($_SESSION['admin']):?>
	<p><a href="/product/mainpage/id/<?=$product['id']?>">
	<?php if($product['main']):?>
	Remove from the Main
	<?php else:?>
	Add To Main
	<?php endif;?>
	</a></p>
	<p><a href="/product/edit/id/<?=$product['id']?>">Edit Product</a></p>
	<p><a href="/product/delete/id/<?=$product['id']?>">Delete Product</a></p>
	<?php endif?>
</div>

<div class="product_list_unit_price"><span>$ <?=$product['price']?> </span> 



		


<a class="add_to_card_button"  id="<?=$product['id']?>" href="#add"></a>




</div>


</div>
<div class="clear"></div>
<?php endif;?> <?php endforeach;?> <?php else:?>
<p>No results</p>

<?php endif;?> 


<div id="Items_per_page">
Items per page:
<?php if($this->count != 20):?> 
<a href="#20" class='count'>20</a> 
<?php else :?>
 <span>20</span> 
 <?php endif?> | <?php if($this->count != 40):?>
<a href="#40" class='count'>40</a> 
<?php else :?> 
<span>40</span> 
<?php endif?>
</div>
<div class="paginator"><?=$this->paginationControl($this->products, 'Sliding', 'my_pagination.phtml'); ?>




</div>
		
</div>
</div>
			<script>
			$(document).ready(function(){
				$('.count').click(function(){
					value = $(this).text();
					window.location.href = '<?= $this->url(array('count'=>null));?>'+'/count/'+value;

				});
			})
			</script>
			
			<script>
			$(document).ready(function(){
				$('.add_to_card_button').click(function(){
					var id = $(this).attr("id");
					
						$.ajax({
							   url: '/cart/add/id/'+id,
							   success: function(){
							   $.ajax({
								   url: '/cart/getcount/',
								   success: function(msg){
								   	$('#cart_items_count').html(msg);
									
								   }
							});	
							   }
						});
					});
				
			})
			</script>


