<p><a href="/cart/clear/">Clear Cart</a></p>





<div id="product_path">
<a href="/">Home</a> &gt; Cart & Checkout
</div>
			<div id="main_container">

				<div id="checkout_stpes">
					<img src="img/checkout_1.gif" alt="">
				</div>
				<div id="shopping_cart">
					<img src="img/cart_big_img.gif" alt="">
					Shopping Cart
				</div>
				<div id="cart_items_first_head">
					<p>Cart Items - To Buy Now</p>

				</div>
				<div id="cart_items_second_head">
					<p class="head_desc">Description</p>
					<p class="head_price">Price</p>
					<p class="head_quantity">Quantity</p>
					<p class="head_amount">Amount</p>
					<p class="head_buttons"></p>

				</div>
			
			
			
				
				
				<?=$this->productsInCart()?>
				
			


				<p>&nbsp;</p>
				<div class="update_quantity">

					<input class="update" value="Update Quantity" type="submit">
				</div>
				<div class="clear"></div>
				<div class="update_quantity">Subtotal : <span class="red_price bold"> USD <?=$this->total_price?></span></div>
				
				
			
				
			<div class="checkout_down">
					<div class="checkout_down_contain">
						<a href="#">«Continue shopping</a>
						<a class="checkout_down_contain_button" href="#"><img src="application/public/img/check_out_account_close.gif" alt=""></a>
					</div>
				</div
				
				<div class="processed_checkout_head">
					<img src="img/check_out_account_open.gif" alt="">
				</div>
				<div class="processed_checkout_container">
					<div class="processed_checkout_right">
						<p class="create_account"><span class="bold">Create a DHgate account</span></p>
						<p class="processed_checkout_right_title">Email Address : </p>
						<p class="processed_checkout_right_text"><input type="text"><img src="img/check_out_account_corret.gif" alt=""></p>
						<p class="small_gray">This will be used to sign into your account.</p>
						<p class="small_gray red_price">Email address is required. Please try again.</p>
						<p class="processed_checkout_right_title">Password : </p>
						<p class="processed_checkout_right_text"><input type="text"><img src="img/check_out_account_corret.gif" alt=""></p>
						<p class="small_gray">Must have 6 to 30 characters and no spaces.</p>
						<p class="small_gray red_price">A password is required. Please try again.</p>
						<p class="processed_checkout_right_title">Re-type Password : </p>
						<p class="processed_checkout_right_text"><input type="text"><img src="img/check_out_account_corret.gif" alt=""></p>
						<p class="small_gray red_price">A password is required. Please try again.</p>
						<p class="processed_checkout_right_title">Nickname : </p>
						<p class="processed_checkout_right_text"><input type="text"><img src="img/check_out_account_corret.gif" alt=""></p>
						<p class="small_gray">Email address is not allowed.</p>
						<p class="small_gray red_price">A nickname is required. Please try again.</p>
						<p class="processed_checkout_right_title">Email Verification Code : </p>
						<p class="processed_checkout_right_text"><input type="text"><img src="img/verifycode.jpg" alt=""><a href="#"><img src="img/check_out_account_refresh.gif" alt=""></a></p>
						
						<p class="small_gray red_price">Verification code is required. Please try again.</p>
					</div>
					<div class="processed_checkout_left">
						<p><span class="bold">Already have an account?</span></p>
						<div class="clear"></div>
						<p>You have an account with DHgate.com, Please login.</p>
						<div class="clear"></div>
						<p><a href="#">Sign in here</a></p>
					</div>
					<div class="sign_up"><input type="submit" value="Sign Up & Check Out"></div>
				</div>
			</div>
				
			<script>
			
			$(document).ready(function(){
				
				$('.delete').click(function(){
					var id = $(this).attr("product_id");
					$("span[product_id='"+id+"']").html('Please wait...');
						$.ajax({
							   url: '/cart/delete/id/'+id,
							   success: function(msg){
							   	//msg ответ от сервера(будем передавать колво товаров в корзине)
								$('#cart_items_count').html(msg);
								$("span[product='"+id+"']").html('<p>Product Deleted From Cart</p>');
							   }
						});
				});
				
				$('.update').click(function(){
					var red_price = 0;
					var products_count = 0;
				
					$('input[class="count"]').each(	function(n,element){
						
						var product_count= $(element).attr('value')-0;
						var product_id = $(element).attr('product_id');	
						var product_price =$(element).attr('price');
						
						
						$.ajax({url: '/cart/update/id/'+product_id+'/count/'+product_count});
						
						
						$('p[product_id="'+product_id+'"]').html('USD '+product_count*product_price);
						red_price=red_price+product_count*product_price;
						products_count += product_count;
					});
					
										 
					$('#cart_items_count').html(products_count);
					$('span[class="red_price bold"]').html('USD '+ red_price);
				});

				
				
			})
			</script>	