<div class="line_center_container"></div>
	<div id="head_center_container">
		<div id="contain_head_center_container">
				<div id="left_contain_head_center_container">
					<a href="#">Home</a> > <a href="#">Online Store</a> > <a href="#">Account Maintenance</a> > Bill To Information
				</div>
		</div>
	</div>
<div class="line_center_container"></div>
	<div id="head_center_container">
		<div id="contain_head_center_container">
			
				<div id="left_contain_head_center_container">
					<a href="#">Account Maintenance</a> / Bill To Information 
				</div>
		</div>
	</div>
<div class="line_center_container"></div>

<div class="circle_buttons">
	<a href=""><img src="/application/public/img/account-.png" alt=""></a>
	<a href=""><img src="/application/public/img/search-a.png" alt=""></a>
</div>
<p class="required">(* = Required)</p>
	<div class="registration_title">Bill To Information</div>
	<div class="clear"></div>
	<form action="/user/edit/id/<?=$this->user->id?>" method="post">
    <p class="register_text">Company Name :</p>
	<p class="register_input"><input type="text" name="company" value="<?=$this->user->company?>"></p>
	<div class="clear"></div>
    <p class="register_text">Title: </p>
	<p class="register_input">
    <select name="title" id="title_field">
        <option value="">none</option>
        <option value="Mr.">Mr.</option>
        <option value="Mrs.">Mrs.</option>
        <option value="Dr.">Dr.</option>
        <option value="Prof.">Prof.</option>
    </select>
    </p>
	<div class="clear"></div>
    <p class="register_text">First Name* :</p>
    <p class="register_input"><input type="text" name="firstname" value="<?=$this->user->firstname?>"></p>
	<div class="clear"></div>
    <p class="register_text">Last Name* :</p>
    <p class="register_input"><input type="text" name="lastname" value="<?=$this->user->lastname?>"></p>
	<div class="clear"></div>
    <p class="register_text">Address * :</p>

    <p class="register_input"><input type="text" name="adress" value="<?=$this->user->adress?>"></p>
	<div class="clear"></div>
    <p class="register_text">Address :</p>
    <p class="register_input"><input type="text" name="adress2" value="<?=$this->user->adress2?>"></p>
	<div class="clear"></div>
    <p class="register_text">City* :</p>
    <p class="register_input"><input type="text" name="city" value="<?=$this->user->city?>"></p>
	<div class="clear"></div>

    <p class="register_text">Zip/Postal Code* :</p>
    <p class="register_input"><input type="text" name="zip" value="<?=$this->user->zip?>"></p>
	<div class="clear"></div>
    <p class="register_text">Country* :</p>
    <p class="register_input">
    <select name="country">
    <?php foreach ($this->countrys as $country):?>
    <?php if($country->id == $this->user->country){
    	$selected = 'selected';
    } else {
    	$selected = '';
    }
    ?>
    	<option class="country" <?=$selected?> value="<?=$country->id?>"><?=$country->name?></value>
    <?php endforeach;?>
    </select>
    </p>
	<div class="clear"></div>
    <p class="register_text">State :</p>
    <p class="register_input">
		<input type="text" name="state" value=<?=$this->user->state?>>
    </p>
	<div class="clear"></div>
    <p class="register_text">Phone* :</p>
    <p class="register_input"><input type="text" name="phone" value="<?=$this->user->zip?>"></p>
	<div class="clear"></div>
    <p class="register_text">Mobile phone :</p>
    <p class="register_input"><input type="text" name="mobilephone" value="<?=$this->user->mobilephone?>"></p>
	<div class="clear"></div>
    <p class="register_text">Fax :</p>
    <p class="register_input"><input type="text" name="fax" value="<?=$this->user->fax?>"></p>
	<div class="clear"></div>
    <p class="register_continue_button">
  		<input type="submit" value="save">
    </p>
</form>
<form action="/user/profile/id/<?=$this->user->id?>">
    <p class="register_continue_button">
  		<input type="submit" value="back">
    </p>
</form>

    <script>
    	$('.country').click(function(){
    		id = $(this).val();
    		 $.ajax({
			   type: "POST",
			   url: "/country/getstate/id/" + id,
			   success: function(msg){
			     $('#state').html(msg);
			   }
			 });
    	});
    </script>
	<div class="clear"></div>
	<div class="delimiter"></div>
	<div class="line_center_container"></div>
	<!-- <div class="delimiter"></div>
	<div class="registration_title">Bank Account Info</div>
    <p class="register_text">Account Holder :</p>
	<p class="register_input"><input type="text" name="company"></p>
	<div class="clear"></div>
    <p class="register_text">Account Number</p>
	<p class="register_input"><input type="text" name="company"></p>
	<div class="clear"></div>
    <p class="register_text">Bank sorting code number :</p>
    <p class="register_input"><input type="text" name="firstname"></p>
	<div class="clear"></div>
    <p class="register_text">Bank Account Type :</p>
    <p class="register_input">
    <select name="title" id="title_field">
        <option value="">none</option>
        <option value="Mr.">Mr.</option>
        <option value="Mrs.">Mrs.</option>
        <option value="Dr.">Dr.</option>
        <option value="Prof.">Prof.</option>
    </select>
    </p>
	<div class="clear"></div>
    <p class="register_text">IBAN :</p>
    <p class="register_input"><input type="text" name="middlename"></p>
	<div class="clear"></div>
    	<div class="delimiter"></div>
	<div class="line_center_container"></div>
    <p class="register_continue_button">
    	<?php // @todo если доебутся сделать нормальную кнопку ?>
     	<input type="submit" value="Save">
    </p> -->
</form>
 <?=$this->message?>
	<div class="delimiter"></div>