	<div class="line_center_container"></div>
				<div id="head_center_container">
					<div id="contain_head_center_container">
						<div id="right_contain_head_center_container"></div>
						<div id="left_contain_head_center_container">
							<a href="#">Home</a> > <a href="#">Online Store</a> > Registration
						</div>
					</div>
				</div>
	<div class="line_center_container"></div>
	<p class="required">(* = Required)</p>
	<div class="registration_title">Customer Information</div>
<?php
if($this->checkout)
{
	$action = '/user/register/checkout/1';
} else {
	$action = '/user/register/';
}
?>	
<form action="<?=$action ?>" method="post">
    <p class="register_text">Mail* : </p> 
	<p class="register_input"><input type="text" name="mail"></p>
	<div class="clear"></div>
    <p class="register_text">login* :</p>
   	<p class="register_input"><input type="text" name="login"></p>
	<div class="clear"></div>
    <p class="register_text">password* :</p>
    <p class="register_input"><input type="password" name="pass"></p>
	<div class="clear"></div>
    <p class="register_text">Confirm Password*" :</p>
    <p class="register_input"><input type="password" name="repass"></p>
	<div class="delimiter"></div>
    <div class="clear"></div>
	<div class="line_center_container"></div>
	<div class="delimiter"></div>
	<div class="registration_title">Bill To Information</div>
    <p class="register_text">Company Name :</p>
	<p class="register_input"><input type="text" name="company"></p>
	<div class="clear"></div>
    <p class="register_text">Title: </p>
	<p class="register_input">
    <select name="title" id="title_field">
        <option value="">none</option>
        <option value="Mr.">Mr.</option>
        <option value="Mrs.">Mrs.</option>
        <option value="Dr.">Dr.</option>
        <option value="Prof.">Prof.</option>
    </select>
    </p>
	<div class="clear"></div>
    <p class="register_text">First Name* :</p>
    <p class="register_input"><input type="text" name="firstname"></p>
	<div class="clear"></div>
    <p class="register_text">Last Name* :</p>
    <p class="register_input"><input type="text" name="lastname"></p>
	<div class="clear"></div>
    <p class="register_text">Address * :</p>
    <p class="register_input"><input type="text" name="adress"></p>
	<div class="clear"></div>
    <p class="register_text">Address :</p>
    <p class="register_input"><input type="text" name="adress2"></p>
	<div class="clear"></div>
    <p class="register_text">City* :</p>
    <p class="register_input"><input type="text" name="city"></p>
	<div class="clear"></div>
    <p class="register_text">Zip/Postal Code* :</p>
    <p class="register_input"><input type="text" name="zip"></p>
	<div class="clear"></div>
    <p class="register_text">Country* :</p>
    <p class="register_input">
    <select name="country">
    <?php foreach ($this->countrys as $country): ?>
    	<option class="country" value="<?=$country->id?>"><?=$country->name?></value>
    <?php endforeach;?>
    </select>
    </p>
    <?php if($_SESSION['admin']):?>
    	<a href="/country/add/">country add</a>
    <?php endif; ?>
	<div class="clear"></div>
    <p class="register_text">State :</p>
    <p class="register_input">
		<input type="text" name="state">
    </p>
	<div class="clear"></div>
    <p class="register_text">Phone* :</p>
    <p class="register_input"><input type="text" name="phone"></p>
	<div class="clear"></div>
    <p class="register_text">Mobile phone :</p>
    <p class="register_input"><input type="text" name="mobilephone"></p>
	<div class="clear"></div>
    <p class="register_continue_button">
    	<?php // @todo если доебутся сделать нормальную кнопку ?>
     	<input type="submit" value="continue">
    </p>
</form>
    <script>
    	$('.country').click(function(){
    		id = $(this).val();
    		 $.ajax({
			   type: "POST",
			   url: "/country/getstate/id/" + id,
			   success: function(msg){
			     $('#state').html(msg);
			   }
			 });
    	});
    </script>
<?=$this->message?>