
<?php
if($this->checkout)
{
	$action = '/user/register/checkout/1';
} else {
	$action = '/user/register/';
}
?>	








<div id="product_path">
<a href="/">Home</a> > <span>Registration</span>
</div>
<div id="main_registration">
<div id="registration">
<h2>Join DHgate.com For Free</h2>
<div id="registration_form">







<?=$this->message ?>
<form action="<?=$action ?>" method="post">

<p class="processed_checkout_right_title">Email Address :</p>
<p class="processed_checkout_right_text">
<input type="text" name="mail">
<img src="/application/public/img/check_out_account_corret.gif" alt=""></p>
<p class="small_gray">This will be used to sign into your account.</p>
<p class="small_gray red_price">Email address is required. Please try again.</p>

<p class="processed_checkout_right_title">Password :</p>
<p class="processed_checkout_right_text">
<input type="password" name="pass">

<img src="/application/public/img/check_out_account_corret.gif" alt=""></p>
<p class="small_gray">Must have 6 to 30 characters and no spaces.</p>
<p class="small_gray red_price">A password is required. Please try again.</p>

<p class="processed_checkout_right_title">Re-type Password :</p>
<p class="processed_checkout_right_text">
<input type="password" name="repass">

<img src="/application/public/img/check_out_account_corret.gif" alt=""></p>
<p class="small_gray red_price">A password is required. Please try again.</p>

<p class="processed_checkout_right_title">Nickname :</p>
<p class="processed_checkout_right_text">
<input type="text" name="login">

<img src="/application/public/img/check_out_account_corret.gif" alt=""></p>
<p class="small_gray">Email address is not allowed.</p>
<p class="small_gray red_price">A nickname is required. Please try again.</p>

<p class="processed_checkout_right_title">Email Verification Code :</p>
<p class="processed_checkout_right_text">
<input type="text">



<img src="/application/public/img/verifycode.jpg" alt=""><a href="#">
<img src="/application/public/img/check_out_account_refresh.gif" alt=""></a></p>

<p><input class="registration_button" type="submit" value="" ></p>
<!--
Чёта похоже я с кнопкой намутил :)

-->

</form>
</div>



<div id="form_sign_in">
<p class="bold">Already have an account?</p>
<p><a href="/user/login/"><img src="/application/public/img/sign_in_button.gif" alt=""></a></p>
<p><a class="bold" href="#">Forgot your password? </a> | <a class="bold" href="#"> Help</a></p>
</div>
</div>

