<div id="help_me">
	<div class="uphelp">Contact Us</div>
	<div class="uphelp_content">
		<table cellspacing="0" cellpadding="0" border="0" class="contactus">
			<tbody><tr>
				<td style="font-weight: 700;">Address:</td>
				<td>6F Dimeng Commercial Building No.3-2, Hua Yuan Road, Haidian District, Beijing, China 100083</td>
			</tr>
			<tr>
				<td style="font-weight: 700;">Telephone:</td>
				<td>86-10-82257676</td>
			</tr>
			<tr>
				<td style="font-weight: 700;">Fax:</td>
				<td>86-10-82025922</td>
			</tr>
			<tr>
				<td style="font-weight: 700;">Office<br/> Hours:</td>
				<td>Mon-Sun 9:00am to 6:00pm (GMT +08:00)</td>
			</tr>
		</tbody></table>
		<p style="margin: 10px 0pt; line-height: 20px; font-size: 12px;">If you have any inquiries about these issues, please email us at  <a href="mailto:service@dhgate.com">service@dhgate.com</a> </p>
	</div>
	<img alt="" src="/application/public/img/right_02.gif"/>
</div>