<div id="help_me">
	<div class="uphelp">Help</div>
	<div class="uphelp_content">
		<p style="margin: 10px; font-size: 12px; color: #004080; font-weight: 700;">What can DHgate do for you?</p>
		<p style="margin: 10px;">At DHgate, we understand the reservations you may have regarding purchasing via the internet. That's why we've taken steps to make your experience hassle free and safe.</p>
		<p style="margin: 10px; font-size: 12px; color: #004080; font-weight: 700;">How can I trust the seller?</p>
		<p style="margin: 10px;"><span style="color: red; font-weight: 700;">Escrow</span> is your guarantee! When you pay for an item at <a href="www.dhgate.com">www.dhgate.com </a>we retain your payment until we receive confirmation from you that you are satisfied with your purchase once it's been delivered. In addition to going through a screening process, sellers can be rated and reviewed by previous buyers allowing you to double check a seller's background and selling history.</p>
		<p style="margin: 10px; font-size: 12px; color: #004080; font-weight: 700;">Where can I find the most at low wholesale prices?</p>
		<p style="margin: 10px;">DHgate is a gateway to China, the world's largest and most diverse market. This gives you the advantage of having access to a huge selection of items ranging from MP3 players, cell phones, shoes, clothing, jewelry, camping gear, etc. The list goes on and on, and they're all at low wholesale prices.</p>
		<p style="margin: 10px; font-size: 12px; color: #004080; font-weight: 700;">What if a misunderstanding occurs - who will help me solve it?</p>
		<p style="margin: 10px;">If you encounter a problem at any time during your transaction, DHgate is happy to help you solve it. We keep in close contact with our customers and have established a process to deal with any disputes.</p>
	</div>
	<img src="/application/public/img/right_02.gif" alt="">
</div>
