
<img
	src="/application/public/img/52312001.gif" alt="">
<div class="center_block_up">
<div class="search_pannel_left"><img
	src="/application/public/img/center_block_left.gif" alt=""></div>
<div id="product_text">Products</div>
<div class="search_pannel_right"><img
	src="/application/public/img/center_block_right.gif" alt=""></div>
</div>
<div class="clear"></div>
<div class="center_block_contain">

<?=$this->mainProduct();?>
<img class="center_block_down"
	src="/application/public/img/center_block_down.gif" alt=""></div>

<div id="center_down_menu_left"><a href="#">Clearance Zone</a></div>
<div id="center_down_menu_middle"><a href="#">Sea Shipping Sale</a></div>
<div id="center_down_menu_right"><a href="#">As Seen On TV</a></div>

<div class="clear"></div>
<div id="content_down_menu"><img
	src="/application/public/img/16811000.gif" alt="">
<p>Get up to 65% on all clearance items including adult and baby
apparel, shoes, jewelry, and consumer electronics. Get the most value
for your dollar here!</p>
<a href="#">Enter Clearance Zone »</a></div>
