
<form action="<?=$this->form->getAction()?>" method="POST">
				<p class="left_text"><span class="align_right">Company name : </span><?=$this->form->company?><span class="normal_gray">(Optional)</span></p>
				<p class="left_text"><span class="align_right"><span class="red_price">*</span>Contact Name : </span><?=$this->form->contact?></p>
				<p class="left_text"><span class="align_right"><span class="red_price">*</span>Address Line 1 :  </span><?=$this->form->address?></p>
				<p class="left_text"><span class="align_right"><span class="red_price">*</span>Address Line 2 :  </span><?=$this->form->address2?><span class="normal_gray">(Optional)</span></p>
				<p class="left_text"><span class="align_right"><span class="red_price">*</span>City :  </span><?=$this->form->city?></p>
				<p class="left_text"><span class="align_right"><span class="red_price">*</span>State / Province :  </span><?=$this->form->state?></p>
				<p class="left_text"><span class="align_right"><span class="red_price">*</span>Country :  </span><?=$this->form->country?></p>
				<p class="left_text"><span class="align_right"><span class="red_price">*</span>Postal Code :  </span><?=$this->form->postal?></p>
				<p class="left_text"><span class="align_right"><span class="red_price">*</span>Phone Number :  </span><?=$this->form->phone?></p>
				<p class="left_text"><span class="align_right">Fax Number  : </span><?=$this->form->fax?><span class="normal_gray">(Optional)</span></p>
				<p><span class="align_right"><?=$this->form->submit?></span></p>
</form>